import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {hashFuente,evaluarExplicacion,cargarExplicacion} from '../src/lib/criollo.mjs';
const a={texto:'Derecho con excepciones.',notas_oficiales:'Ver art. 2',estado_actual:'documento_actualizado'};
const r={articulo:'1',hash_fuente:hashFuente(a),resumen:'Texto',estado:'borrador',dependencias:[],revision:null};
const resolve=()=>a;
test('borrador no expone texto en producción',()=>assert.deepEqual(evaluarExplicacion(r,a,resolve),{estado:'pendiente',registro:null}));
test('preview identifica borrador, no aprobado',()=>assert.equal(evaluarExplicacion(r,a,resolve,true).estado,'borrador'));
test('aprobación requiere responsable y fecha',()=>assert.equal(evaluarExplicacion({...r,estado:'aprobado'},a,resolve).registro,null));
test('aprobado con revisión real se renderiza',()=>assert.equal(evaluarExplicacion({...r,estado:'aprobado',revision:{responsable:'Revisor de prueba',fecha:'2026-09-30'}},a,resolve).estado,'aprobado'));
for(const campo of ['texto','notas_oficiales','estado_actual'])test(`cambio en ${campo} oculta explicación`,()=>assert.equal(evaluarExplicacion(r,{...a,[campo]:'Cambio'},resolve,true).estado,'desactualizado'));
test('dependencia cambiada oculta explicación',()=>assert.equal(evaluarExplicacion({...r,dependencias:[{norma:'x',articulo:'2',hash:'viejo'}]},a,resolve,true).estado,'desactualizado'));
test('dependencia desaparecida oculta explicación',()=>assert.equal(evaluarExplicacion({...r,dependencias:[{norma:'x',articulo:'2',hash:hashFuente(a)}]},a,()=>undefined,true).estado,'desactualizado'));
test('sin texto y derogado no tienen explicación',()=>{for(const texto of ['', '(Derogado).'])assert.equal(evaluarExplicacion(r,{...a,texto},resolve,true).estado,'no-disponible')});
test('retirado no tiene explicación',()=>assert.equal(cargarExplicacion('constitucion','7',a,resolve,{retirado:true}).estado,'no-disponible'));
test('ausente no fabrica texto',()=>assert.equal(evaluarExplicacion(null,a,resolve).estado,'ausente'));
test('80 aprobados con contraste trazable y vigentes frente a api',()=>{let count=0;const resolver=(s,id)=>fs.readFileSync(`data/${s}.jsonl`,'utf8').split('\n').filter(Boolean).map(JSON.parse).find(a=>String(a.articulo).toLowerCase()===id);for(const file of fs.readdirSync('explicaciones'))for(const r of fs.readFileSync(`explicaciones/${file}`,'utf8').trim().split('\n').map(JSON.parse)){count++;const slug=file.replace('.jsonl','');assert.equal(r.estado,'aprobado');assert.ok(r.revision.responsable&&r.revision.fecha&&r.revision.obra&&r.revision.url_obra&&r.revision.pasaje&&r.revision.respaldo);assert.equal(evaluarExplicacion(r,resolver(slug,r.articulo),resolver,false).estado,'aprobado');assert.ok(r.fuente.startsWith('https://www.impo.com.uy/'));assert.ok(r.resumen&&r.importante&&r.termino)}assert.equal(count,80)});

test('tanda 2 tiene 50 artículos únicos y criterio de contraste',()=>{const esperados={constitucion:37,'ley-18437':21,'codigo-ninez-adolescencia':22};for(const [slug,count] of Object.entries(esperados)){const rows=fs.readFileSync(`explicaciones/${slug}.jsonl`,'utf8').trim().split('\n').map(JSON.parse);assert.equal(rows.length,count);assert.equal(new Set(rows.map(r=>r.articulo)).size,count);for(const r of rows)assert.equal(r.revision.responsable,'Contraste documental asistido')}});
